version: '3'
services:
  redis1:
    image: redis
    container_name: redis1
    ports: 
      - "6379:6379"
    volumes:
      - ./redis1/data:/data
      - ./redis1/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis2:
    image: redis
    container_name: redis2
    ports: 
      - "6377:6377"
    volumes:
      - ./redis2/data:/data
      - ./redis2/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf